### ISSUE TITLE
Razorpay New UI Beta

### ISSUE THREAD

**Issue by raoabishay** [razorpay/razorpay-cordova#10]
Can we have a separate branch for testing the new UI as shown [here](http://razorpay.com/demo)?
I am keen on trying the new UI for our app and this would also be an excellent way of identifying issues that are specific to Cordova/Ionic.

**Comment by pronav** [comment]
Hi Abhishay, we've rolled out new UI for test keys. Please try out and do report if you encounter any issues! Any feedback about UI is also welcome.

**Comment by raoabishay** [comment]
Yes, the new UI appears now. Thanks much!
