### ISSUE TITLE
How to integrate in phaser 

### ISSUE THREAD

**Issue by balamurugan1991** [razorpay/razorpay-cordova#100]
I don't how to add it in **phaser es6**. i install plugin using your command, next import command then i don't know what are the files need to add.i need  your instruction. I am using **phaser with cordova for android**. Guide me

Finally how to run the examples. Please add it in the instruction.

**Comment by balamurugan1991** [comment]
AnyBody There...

**Comment by Nautiyalsachin** [comment]
Hey @balamurugan1991, hope you are able to add the phaser es6, for reference you can try this [example](https://github.com/fbaldo31/cordova-phaser). I hope you have already fixed this, closing this issue for time being, let me know if this issue still persists, you can re-open the issue for any query or any further assistance.
