### ISSUE TITLE
App rejected because of razorpay android.permission.RECEIVE_SMS

### ISSUE THREAD

**Issue by vibinflogesoft** [razorpay/razorpay-cordova#101]
* **Common to Both platforms :-**

  - [x] I have gone through the README(https://github.com/razorpay/razorpay-cordova)
  - [x] I have searched for a similar issue (https://github.com/razorpay/razorpay-cordova/issues)
  - [x] I am using the latest version of our framework (https://github.com/razorpay/razorpay-cordova/releases)
  - [x] I have cleaned my project.

* **Specific to iOS Users :-**
  - [x] I have modified the module map as specified in the readme (https://github.com/razorpay/razorpay-cordova)
  - [x] I have deleted the contents of the derived data folder and rebuild it.

**Comment by vibinflogesoft** [comment]
Based on our review, we found your app’s expressed user experience did not match your declared core functionality {SMS-based financial transactions (e.g., 5 digit messages), and related activity including OTP account verification for financial transactions and fraud detection}. Please remove these permissions from your app.

**Comment by vibinflogesoft** [comment]
****

**Comment by pronav** [comment]
Which plugin version are you using?

**Comment by vibinflogesoft** [comment]
@pronav V1.4.1

**Comment by pronav** [comment]
We had removed SMS permission since January this year, please update your plugin to 1.4.4 and see if it works.
