### ISSUE TITLE
Razorpay Subscription not working 

### ISSUE THREAD

**Issue by nagarajns** [razorpay/razorpay-cordova#103]
* **Common to Both platforms :-**

  - [ ] I have gone through the README(https://github.com/razorpay/razorpay-cordova)
  - [ ] I have searched for a similar issue (https://github.com/razorpay/razorpay-cordova/issues)
  - [ ] I am using the latest version of our framework (https://github.com/razorpay/razorpay-cordova/releases)
  - [ ] I have cleaned my project.

* **Specific to iOS Users :-**
  - [ ] I have modified the module map as specified in the readme (https://github.com/razorpay/razorpay-cordova)
  - [ ] I have deleted the contents of the derived data folder and rebuild it.
  

## Screenshots 

Subscription is not working in ionic 4

**Comment by nagarajns** [comment]
I have tried with normal payment method, its working fine.. 
But when i am creating authorization for subscription that time it breaks

![razorpay_issue](https://user-images.githubusercontent.com/12527807/58196634-5d3c4a80-7ce8-11e9-9c95-4db5b9504874.png)

**Comment by pronav** [comment]
What options are you passing to plugin for subscription?

**Comment by nagarajns** [comment]
i am passing options like below, I am having data in *auth* variable..

const options = {
        'key': auth.razorpay_key,
        'subscription_id': auth.subscription_id,
        'name': auth.name,
        'description': auth.description,
        'prefill': {
          'email': '',
          'contact': auth.prefill.contact,
          'name': auth.prefill.name
        },
        'notes': {
          'subscription_id': auth.subscription_id,
        },
      };

 RazorpayCheckout.on('payment.success', this.razorPaySuccess);
      RazorpayCheckout.on('payment.cancel', this.razorPayError);
      RazorpayCheckout.open(options);

**Comment by pronav** [comment]
can you post a sample subscription-id?

**Comment by nagarajns** [comment]
const options = {
      'key': 'rzp_test_kJYAbHXu2QZzI3',
      'subscription_id': 'sub_CYdaZ1SKpTvCPr',
      'name': 'App',
      'description': 'Description',
      'prefill': {
        'email': '',
        'contact': '9738404686',
        'name': 'Nagaraj'
      },
    };

**Comment by pronav** [comment]
Card payments are disabled for your account, please raise this with support@razorpay.com and get card as well as subscription feature enabled for your account.
