### ISSUE TITLE
[bug] 'Razorpay/Razorpay.h' file not found

### ISSUE THREAD

**Issue by indraraj26** [razorpay/razorpay-cordova#105]
* **Common to Both platforms :-**

  - [x ] I have gone through the README(https://github.com/razorpay/razorpay-cordova)
  - [x ] I have searched for a similar issue (https://github.com/razorpay/razorpay-cordova/issues)
  - [ x] I am using the latest version of our framework (https://github.com/razorpay/razorpay-cordova/releases)
  - [x ] I have cleaned my project.

* **Specific to iOS Users :-**
  - [ x] I have modified the module map as specified in the readme (https://github.com/razorpay/razorpay-cordova)
  - [ ]x I have deleted the contents of the derived data folder and rebuild it.
  

## IDE Specs

   OS         : macOS High Sierra
   Xcode      : Xcode 10.1 Build version 10B61

"com.razorpay.cordova": "^1.4.5",

**Comment by pronav** [comment]
We'll looking into it. Meanwhile:
1. Try changing it to `Razorpay/Razorpay-swift.h` wherever it's being referred to.
2. Try using version `1.4.3` of plugin, current version is compatible with xcode 10.2

**Comment by indraraj26** [comment]
I tried 1.4.3 and 1.4.1 but still it is showing this error 'Razorpay/Razorpay.h' file not found
