### ISSUE TITLE
RazorpayCheckout.open doesn't open modal in IOS

### ISSUE THREAD

**Issue by charumahajan** [razorpay/razorpay-cordova#107]
The app doesn't do anything after RazorpayCheckout.open(options, successCallback, cancelCallback);
no console error, no loading. This issue is only in IOS . On other platforms its working fine.

**Comment by Nautiyalsachin** [comment]
Hey @charumahajan, we have released a new version with the fix for this, please update it to the latest version. 

For now closing this issue, feel free to reopen or add a new comment on the same for any additional query.

**Comment by Nautiyalsachin** [comment]
https://github.com/razorpay/razorpay-cordova/issues/108
