### ISSUE TITLE
Not Expand payment Description text into multiline.Please provide the solution in ionic3

### ISSUE THREAD

**Issue by prasanta12** [razorpay/razorpay-cordova#109]
* **Common to Both platforms :-**

  - [ ] I have gone through the README(https://github.com/razorpay/razorpay-cordova)
  - [ ] I have searched for a similar issue (https://github.com/razorpay/razorpay-cordova/issues)
  - [ ] I am using the latest version of our framework (https://github.com/razorpay/razorpay-cordova/releases)
  - [ ] I have cleaned my project.

* **Specific to iOS Users :-**
  - [ ] I have modified the module map as specified in the readme (https://github.com/razorpay/razorpay-cordova)
  - [ ] I have deleted the contents of the derived data folder and rebuild it.

**Comment by Nautiyalsachin** [comment]
Hi @prasanta12, please try this [sample app](https://github.com/razorpay/razorpay-cordova-sample-app/tree/master/rzp-ionic3-example) which is in ionic3. Let me know if you need any other assistance, closing this issue now.
