### ISSUE TITLE
Razopay.framework:- Following binaries are incompatible version of swift erron in ionic3?

### ISSUE THREAD

**Issue by kapilSoni101** [razorpay/razorpay-cordova#110]
Hi team,
I have generating archive from Xcode 10.0 but I got above error in the console.actually I have implemented payment getway via razopay plugin but I got error.

**I tried below solution**
1st :- eabled bit code from build setting
2nd :- change swift version 4to 4.2 due to razopay compiled with 4.2 version.
![ios](https://user-images.githubusercontent.com/26578635/65898548-6abcbc00-e3cf-11e9-9b86-8e2790eb2a28.jpeg)

#version:
Xocde 10.0
Swift 4.2
Ionic 3
Please team tell me how to fix above error I stuck above error from 2days?

**Comment by Nautiyalsachin** [comment]
Hi @kapilSoni101, we have fixed this issue in our latest update, I'll ask you to update your Xcode and razorpay-pod also. You can see the updated readme for more detailed steps. 

Closing this issue now, feel free to re-open or create a new issue or comment on the same issue, if you have any other additional queries.
