### ISSUE TITLE
Build fails on xcode 11.2.1

### ISSUE THREAD

**Issue by tusharvikky** [razorpay/razorpay-cordova#116]
Hello,

I got the following error while running on iOS. Android works fine. 

```
dyld: Library not loaded: @rpath/Razorpay.framework/Razorpay
  Referenced from: /var/containers/Bundle/Application/6688F2E5-F805-4261-BFCD-26FFC207E1E6/App Demo.app/App Demo
  Reason: image not found
```

Could you please help debug the issue. Waiting for the app to release.

Please let me know if you find any issue.

Regards

**Comment by pramodjaypore** [comment]
struggling for the same .

**Comment by pramodjaypore** [comment]
for me below fix is working
1) blank the main interface option  under general
2) For "Razorpay.Framework" select Embed & sign  under  general section

**Comment by tusharvikky** [comment]
Tried that doesn't work. When we trigger the RazorPay plugin. It just shows white screen.

**Comment by roushankumar01** [comment]
Error solved with this solution.
>Install cordova plugin add com.razorpay.cordova@1.4.5
>import <Razorpay-swift.h>
>In project Setting: General> Frameworks, Libraries, and Embedded Content> Razorpay.framework to Embed and Signin or Embed without Signing

**Comment by Nautiyalsachin** [comment]
Hey @tusharvikky, sorry for the late reply 😅, as @roushankumar01 has suggested, please update to the latest Cordova version, this will definitely fix this issue. 

Closing this issue now, let me know if you need further assistance. 

Regards, Sachin
