### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by dhanan85** [razorpay/razorpay-cordova#118]
I am trying to integrate Razorpay cordova plugin in my ionic app. It works find for Android. But for iOS I am getting below error when I run the app in Xcode. I am unable to proceed further. Please help me resolve the same. FYI, I have integrated as per the steps mentioned in the integration video and have added Razorpay framework in "Embedded Binaries" and have updated "Always Embed Swift Standard Libraries" to "Yes"

**Error Msg:**
dyld: Library not loaded: @rpath/libswiftCore.dylib

  Referenced from: /Users/<user>/Library/Developer/CoreSimulator/Devices/B12116FD-C014-41B6-A5BF-6CEE7F079850/data/Containers/Bundle/Application/A76F064E-8CCA-4F93-A6CC-6E2C140CC231/The SICA.app/Frameworks/Razorpay.framework/Razorpay

  Reason: image not found

**IDE  Specs**
Xcode: 10.1
Swift Version: 4.2.1
Razorpay Version: 1.4.8 (com.razorpay.cordova)

**Screenshots** 
![swiftcode](https://user-images.githubusercontent.com/14245648/72985710-90e9ea00-3e0c-11ea-9ac6-ad6b1dfd191d.PNG)
![Embedded](https://user-images.githubusercontent.com/14245648/72985722-96473480-3e0c-11ea-80ed-e7963a83cab3.PNG)

**Comment by dhanan85** [comment]
Hi,

Expecting an update on this issue pls

**Comment by rickyh2007** [comment]
Same error here, does anyone has a solution to it?

**Comment by Nautiyalsachin** [comment]
Hey @dhanan85, @rickyh2007, we have created a permanent solution for this issue and for implementing the fix you have to update our Razorpay Cordova plugin to the latest version, please update it and also update the razorpay-pod. 

Closing this issue now, feel free to re-open or add comments for any additional queries.
