### ISSUE TITLE
Payments made through RazorpayCheckout (ionic) needs to be Authorized in dashboard

### ISSUE THREAD

**Issue by pankajtechtrail** [razorpay/razorpay-cordova#119]
Hi,
I am using Ionic plugin RazorpayCheckout. The payments made through this plugin needs to be authorized in the razorpay dashboard else it will get refunded back.
When I searched on the net the reason why the payments needs to be authorized, I came to know that the RazorpayCheckout doesnot create order-id but directly makes the payment. Due to which the transaction needs to be authorized from dashboard.
What options I need to pass to RazorpayCheckout for order-id creation or resolving this issue.

**Comment by kiranramsingh** [comment]
Facing similar issue, please help what can be the fix

**Comment by Nautiyalsachin** [comment]
Hi, for creating an order id, you can go through this link - https://razorpay.com/docs/payment-gateway/orders/.

Let me know if you guys need further assistant.

**Comment by pankajtechtrail** [comment]
> Facing similar issue, please help what can be the fix

I found fix in earlier discussion thread.
https://github.com/razorpay/razorpay-cordova/issues/102

**Comment by pankajtechtrail** [comment]
I found fix in earlier discussion thread.
https://github.com/razorpay/razorpay-cordova/issues/102
