### ISSUE TITLE
Payment failed when minimizing app to get OTP on credit card payment ?

### ISSUE THREAD

**Issue by chinthu** [razorpay/razorpay-cordova#128]
* **Common to Both platforms :-**

  - [x] I have gone through the README(https://github.com/razorpay/razorpay-cordova)
  - [x] I have searched for a similar issue (https://github.com/razorpay/razorpay-cordova/issues)
  - [x] I am using the latest version of our framework (https://github.com/razorpay/razorpay-cordova/releases)
  - [x] I have cleaned my project.
  - [x] I have gone through FAQ's (https://github.com/razorpay/razorpay-cordova/wiki/FAQ).

* **Specific to iOS Users :-**
  - [ ] I have modified the module map as specified in the readme (https://github.com/razorpay/razorpay-cordova)
  - [ ] I have deleted the contents of the derived data folder and rebuild it.

**Comment by Nautiyalsachin** [comment]
Hi @chinthu, the above details are not giving any useful information, please add more details like device name, os type, plugin versions, etc. Closing this issue now, feel free to reopen it or add comments or create a new issue if you have any other queries.
