### ISSUE TITLE
Cannot Install on iOS

### ISSUE THREAD

**Issue by theavijitsarkar** [razorpay/razorpay-cordova#130]
* **Common to Both platforms :-**

  - [x ] I have gone through the README(https://github.com/razorpay/razorpay-cordova)
  - [x] I have searched for a similar issue (https://github.com/razorpay/razorpay-cordova/issues)
  - [x] I am using the latest version of our framework (https://github.com/razorpay/razorpay-cordova/releases)
  - [x] I have cleaned my project.
  - [x] I have gone through FAQ's (https://github.com/razorpay/razorpay-cordova/wiki/FAQ).

* **Specific to iOS Users :-**
  - [x] I have modified the module map as specified in the readme (https://github.com/razorpay/razorpay-cordova) 
Nothing like this exists
  - [x ] I have deleted the contents of the derived data folder and rebuild it.
  Remove the platform 4-5 times

## IDE Specs
Xcode 11.3
Build version 11C29

Plugin List
com.pylonproducts.wifiwizard 0.2.11 "WifiWizard"
com.razorpay.cordova 0.16.1 "RazorpayCheckout"
cordova-background-geolocation 3.4.2 "BackgroundGeolocation"
cordova-plugin-android-wifi-manager 1.0.0 "Android WifiManager"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-background-fetch 5.6.1 "CDVBackgroundFetch"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-camera 4.1.1-dev "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-cocoapod-support 1.6.2 "Cordova CocoaPods Dependency Support"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-email 1.2.7 "EmailComposer"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-fastclick 1.0.0 "FastClick"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebasex 9.0.1-cli "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googleplayservices-check 1.0.0 "GooglePlayServicesCheck"
cordova-plugin-ios-longpress-fix 1.1.0 "iOS LongPress Fix"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-uniquedeviceid 1.3.1 "UniqueDeviceID"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.6.4 "SocialSharing"
cordova.plugins.diagnostic 5.0.1 "Diagnostic"
es6-promise-plugin 4.1.0 "Promise"
phonegap-plugin-barcodescanner 8.1.0 "BarcodeScanner"
wifiwizard2 3.1.1 "WifiWizard2"

Cordova V :  9.0.0 (cordova-lib@9.0.1)
 ios 5.1.1

## Retro Steps

Create a cordova app
git clone https://github.com/razorpay/razorpay-cordova
cordova build ios

## Error

/Applications/MAMP/htdocs/regularli-neo-v2/src-cordova/platforms/ios/Regular.li/Plugins/com.razorpay.cordova/Main.m:4:3: error: unknown type
      name 'Razorpay'
  Razorpay *razorpay;
  ^
/Applications/MAMP/htdocs/regularli-neo-v2/src-cordova/platforms/ios/Regular.li/Plugins/com.razorpay.cordova/Main.m:19:15: error: use of
      undeclared identifier 'Razorpay'
  razorpay = [Razorpay initWithKey:(NSString *)[options objectForKey:@"key"]
              ^
/Applications/MAMP/htdocs/regularli-neo-v2/src-cordova/platforms/ios/Regular.li/Plugins/com.razorpay.cordova/Main.m:27:1: warning: 
      implementing deprecated method [-Wdeprecated-implementations]
- (void)onPaymentError:(int)code
^
In module 'Razorpay' imported from /Applications/MAMP/htdocs/regularli-neo-v2/src-cordova/platforms/ios/Regular.li/Plugins/com.razorpay.cordova/Main.h:2:
/Applications/MAMP/htdocs/regularli-neo-v2/src-cordova/platforms/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Headers/Razorpay-Swift.h:1168:1: note: 
      method 'onPaymentError:description:andData:' declared here
- (void)onPaymentError:(int32_t)code description:(NSString * _Nonnull)str andData:(NSDictionary * _Nullable)response SWIFT_DEPRECATE...
^
/Applications/MAMP/htdocs/regularli-neo-v2/src-cordova/platforms/ios/Regular.li/Plugins/com.razorpay.cordova/Main.m:9:17: warning: class
      'Main' does not conform to protocol 'ExternalWalletSelectionProtocol' [-Wprotocol]
@implementation Main
                ^
/Applications/MAMP/htdocs/regularli-neo-v2/src-cordova/platforms/ios/Regular.li/Plugins/com.razorpay.cordova/Main.m:9:17: note: add stubs
      for missing protocol requirements
@implementation Main
                ^
2 warnings and 2 errors generated.

** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Users/av/Library/Developer/Xcode/DerivedData/Regular.li-doelncjsbarxwjbxovoukpfiwpuf/Build/Intermediates.noindex/ArchiveIntermediates/Regular.li/IntermediateBuildFilesPath/Regular.li.build/Debug-iphoneos/Regular.li.build/Objects-normal/armv7/Main-ad16fcefedec8afb3d3fdb0132c5c0ff35fd86ef44d32d16e70b76a9ff977c77.o /Applications/MAMP/htdocs/regularli-neo-v2/src-cordova/platforms/ios/Regular.li/Plugins/com.razorpay.cordova/Main.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Note: I Checked out the Embeds in xcode but there is nothing there.

**Comment by Nautiyalsachin** [comment]
Hi @theavijitsarkar, can you add this line `typedef RazorpayCheckout Razorpay;` at path 
`/Applications/MAMP/htdocs/regularli-neo-v2/src-cordova/platforms/ios/Regular.li/Plugins/com.razorpay.cordova` in `Main.h`.

**Comment by theavijitsarkar** [comment]
Thanks it worked

**Comment by Nautiyalsachin** [comment]
We have updated the package with the fix, you can update it now. the latest version is v1.4.10.

**Comment by asif986** [comment]
Using the Ionic cordova project in razorpay integration i got solution. for @Nautiyalsachin  modified the some steps.
1. update the razorpay pod. go to the podfile  update this line.
