### ISSUE TITLE
Integration with React

### ISSUE THREAD

**Issue by webacers** [razorpay/razorpay-cordova#133]
Hi, 
I am build a hybrid app using Ionic 5 and have used capacitor and React. Now I want to integrate this plugin.

I am getting RazorpayCheckout undefined error. 

Is there anyway to solve this issue? 

Thanks.

**Comment by Nautiyalsachin** [comment]
@webacers : We are only supporting Cordova and not capacitor. If you want to create your plugin in react-native then please use [react-native-razorpay](https://github.com/razorpay/react-native-razorpay) plugin.
