### ISSUE TITLE
How to use this plugin for Subscriptions in RazorPay

### ISSUE THREAD

**Issue by IonicDeveloper2** [razorpay/razorpay-cordova#134]
* **Common to Both platforms :-**

  - [x] I have gone through the README(https://github.com/razorpay/razorpay-cordova)
  - [ ] I have searched for a similar issue (https://github.com/razorpay/razorpay-cordova/issues)
  - [ ] I am using the latest version of our framework (https://github.com/razorpay/razorpay-cordova/releases)
  - [ ] I have cleaned my project.
  - [x] I have gone through FAQ's (https://github.com/razorpay/razorpay-cordova/wiki/FAQ).

* **Specific to iOS Users :-**
  - [ ] I have modified the module map as specified in the readme (https://github.com/razorpay/razorpay-cordova)
  - [ ] I have deleted the contents of the derived data folder and rebuild it.

**Comment by Nautiyalsachin** [comment]
Hi @IonicDeveloper2, here are our documentation for [Subscription](https://razorpay.com/docs/subscriptions/), 

Closing this issue now due to incomplete information, feel free to reopen the issue, or add any comments on this for any other information.
