### ISSUE TITLE
Doesn't work in Samsung tablet

### ISSUE THREAD

**Issue by zubinraja** [razorpay/razorpay-cordova#136]
## Description

Razorpay plugin with ionc3 works well in android devices, but in tablets it keeps loading and nothing happens afterwards. 

## Razorpay Package Version :
"com.razorpay.cordova": "git+https://github.com/razorpay/razorpay-cordova.git",

## Java and Gradle Version (android) :
java version "1.8.0_211"
Gradle 6.0.1

### What you did:

After successful testing of razorpay plugin in mobile device, tried same in tablet, it didn't worked and keep showing loading as screenshot attached. 

### What happened:

See screenshot
![WhatsApp Image 2020-06-18 at 10 05 44 AM](https://user-images.githubusercontent.com/21122914/85020225-a251db00-b18d-11ea-9a9a-7894c061d1f8.jpeg)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by Nautiyalsachin** [comment]
@sumedht : Can you help here?
