### ISSUE TITLE
error:  RazorpayCheckout is not defined

### ISSUE THREAD

**Issue by Priya-mk** [razorpay/razorpay-cordova#137]
im using cordova hybrid app (angular 7), showing RazorpayCheckout is not defined

**Comment by AYAN249** [comment]
You can refer to this GitHub link this should work fine https://github.com/razorpay/razorpay-cordova-sample-app

**Comment by Nautiyalsachin** [comment]
Thanks @AYAN249, Let me know @Priya-mk if this issue still persists. Closing the issue now.
