### ISSUE TITLE
Minor usability issue on iPhone

### ISSUE THREAD

**Issue by vishnushelar** [razorpay/razorpay-cordova#14]
After entering card details, when I clicks on of text box to hide keypad that time keypad is not going down. When keypad is visible that time pay button is not visible on screen. To click on pay button we have to scroll the screen.This issue is coming on iPhone.

Expected result : When user clicks on outside of text box that time keypad should go down. I am attaching video for reference.  
[iphone bug.zip](https://github.com/razorpay/razorpay-cordova/files/331633/iphone.bug.zip)

**Comment by akshaybhalotia** [comment]
Thanks for pointing out the issue @vishnushelar , we will roll out a fix for this soon. This would be an OTA update, and won't require SDK update.

**Comment by akshaybhalotia** [comment]
@vishnushelar This has been fixed. Now the users get a `Done` button on the keyboard to dismiss the keyboard, as is the standard practice for iOS devices.

**Comment by vishnushelar** [comment]
@akshaybhalotia I can't see go button. Check following screen shot.

![2016-06-29](https://cloud.githubusercontent.com/assets/5018918/16454063/c5cc12f4-3e2c-11e6-9806-e06ef8347340.png)

**Comment by vishnushelar** [comment]
I don't have access to open this issue. Please check above screen shot.
BTW thanks for support.

**Comment by akshaybhalotia** [comment]
Not sure what is happening in your case @vishnushelar . Check my screen shots.

![simulator screen shot 29-jun-2016 7 11 15 pm](https://cloud.githubusercontent.com/assets/9196911/16454266/a2d6d9b8-3e2d-11e6-8c5b-11ee8cd10e7a.png)
![simulator screen shot 29-jun-2016 7 11 30 pm](https://cloud.githubusercontent.com/assets/9196911/16454263/a2d26be4-3e2d-11e6-843a-4c26cd6bfffa.png)
![simulator screen shot 29-jun-2016 7 11 21 pm](https://cloud.githubusercontent.com/assets/9196911/16454264/a2d33a88-3e2d-11e6-8ca8-b24896791869.png)
![simulator screen shot 29-jun-2016 7 11 26 pm](https://cloud.githubusercontent.com/assets/9196911/16454265/a2d4b78c-3e2d-11e6-80c3-4fef96b3434d.png)

**Comment by vishnushelar** [comment]
ok.
@akshaybhalotia which ios version you are using ?

**Comment by akshaybhalotia** [comment]
This is iOS version 9.3, iOS SDK version 0.11.4

**Comment by vishnushelar** [comment]
ok.
It is working on iOS version 9.3. But Done button is not coming on IOS 8.3

**Comment by akshaybhalotia** [comment]
We'll check that

**Comment by akshaybhalotia** [comment]
@vishnushelar Unfortunately, we are not able to replicate the issue even on iOS 8.3 running on Cordova project. Please refer screenshots.

<img width="765" alt="screen shot 2016-06-30 at 12 30 03 pm" src="https://cloud.githubusercontent.com/assets/9196911/16479543/b4ce961a-3ebe-11e6-84b5-ea9b2b716b11.png">

<img width="323" alt="screen shot 2016-06-30 at 12 27 48 pm" src="https://cloud.githubusercontent.com/assets/9196911/16479553/b9634720-3ebe-11e6-91c4-b15d769b908d.png">

<img width="322" alt="screen shot 2016-06-30 at 12 28 16 pm" src="https://cloud.githubusercontent.com/assets/9196911/16479563/be66c436-3ebe-11e6-8c77-6f9ff53e38c3.png">

**Comment by gnprabhurightclick** [comment]
I removed the plugin from the ionic project and then added it again. Following attached is a screenshot of the iphone 6 simulator running on iOS 9.3.
<img width="376" alt="screen shot 2016-06-30 at 1 08 04 pm" src="https://cloud.githubusercontent.com/assets/20127768/16480462/0164ee34-3ec4-11e6-8add-eb78b581668a.png">

**Comment by pronav** [comment]
Can you check if "done" button appears in Safari browser while visiting [razorpay.com/demo](this page). If it does, could be something specific to your app.

**Comment by akshaybhalotia** [comment]
As a work around, you could install [Keyboard plugin] (https://www.npmjs.com/package/ionic-plugin-keyboard) and use `window.cordova.plugins.Keyboard.hideKeyboardAccessoryBar(false);` to force the input accessories on keyboard.
