### ISSUE TITLE
Issue while integrating Razorpay in ionic 3 iOS platform

### ISSUE THREAD

**Issue by amityyChopra** [razorpay/razorpay-cordova#141]
Do I need to code in this file, as suggested for iOS native SDK? Please help because error is coming whenever I am trying to integrate Razorpay.

![Screenshot 2020-07-22 at 6 03 43 PM](https://user-images.githubusercontent.com/26737083/88176961-b2a21d80-cc45-11ea-960d-090173ef6b18.png)
<!--
------ 👆 Click "Preview"!

**Comment by Nautiyalsachin** [comment]
Hey @amityyChopra, you are missing `#import <Razorpay/Razorpay-Swift.h>` next to the `#import <Main.h>`

Also, I would suggest you to update your plugin to the latest version if any available, 

Closing this issue now, feel free to reopen or create a new issue for any additional information.
