### ISSUE TITLE
App Crashes after razorpay

### ISSUE THREAD

**Issue by ladaniavadh** [razorpay/razorpay-cordova#142]
If facing different type of issue that if storage of device is near to full then app is getting restart and order not placed and amount deduct.

On callback of razorpay error is showing that, after payment razorpay should force app to resume instead of restart.

Has anyone face this type of issue?

**Comment by AYAN249** [comment]
You can refer to our sample Cordova sample app: https://github.com/razorpay/razorpay-cordova-sample-app/tree/master/rzp-ionic3-example

**Comment by sumedht** [comment]
@ladaniavadh Have u tried with our sample app? does it behave in the same manner?
Can u share more details like which version of SDK u r using?

**Comment by vivekshindhe** [comment]
Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
