### ISSUE TITLE
Trying to integrate razor pay for ios

### ISSUE THREAD

**Issue by 4blocksinc** [razorpay/razorpay-cordova#143]
Im trying to integrate razor pay for iOS.
 Phonegap Version 9
<plugin name="com.razorpay.cordova" spec="https://github.com/razorpay/razorpay-cordova.git"/>
this is what im using in config.xml file
when i try to build the ipa im getting the following error.
Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: com.razorpay.cordova

Log File: 
The following build commands failed:
	CompileC /Library/Developer/Xcode/DerivedData/Namma_Basket-amalbiytnwtamnersjoqjggsiuwo/Build/Intermediates.noindex/ArchiveIntermediates/Namma\ Basket/IntermediateBuildFilesPath/Namma\ Basket.build/Release-iphoneos/Namma\ Basket.build/Objects-normal/armv7/Main-58EC90E0C4DC92A1.o Namma\ Basket/Plugins/com.razorpay.cordova/Main.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

**Comment by 4blocksinc** [comment]
Url used for plugin addition - https://github.com/razorpay/razorpay-cordova.git

**Comment by Nautiyalsachin** [comment]
Hi @4blocksinc, can you run `cordova build ios --verbose` and share the output here. Right now, shared logs is not helping.

**Comment by 4blocksinc** [comment]
@Nautiyalsachin Im using Adobe phone gap build to create the builds

**Comment by Nautiyalsachin** [comment]
@4blocksinc, can you share the logs here in more details?

**Comment by 4blocksinc** [comment]
![phonegap log](https://user-images.githubusercontent.com/19328801/96829971-37285600-1458-11eb-9dfd-75b455d4b478.png)

**Comment by Nautiyalsachin** [comment]
@4blocksinc, Are you using Xcode 12 ?

**Comment by 4blocksinc** [comment]
No,im not using a Mac to create create the ipa,  im using Adobe phone gap build to create the ipa

**Comment by Nautiyalsachin** [comment]
@4blocksinc, Please download Xcode in your system as you may have to add the asked changes here - https://github.com/razorpay/razorpay-cordova/wiki/FAQ.

**Comment by Nautiyalsachin** [comment]
Closing this issue due to no response, feel free to re-open or add comments.
