### ISSUE TITLE
'Razorpay/Razorpay-Swift.h' file not found

### ISSUE THREAD

**Issue by imromec** [razorpay/razorpay-cordova#144]
## Description

Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest Razorpay Cordova plugin release to make sure your issue has not already been fixed. 

## Razorpay Package Version :
Open `Package.json`. > Copy `com.razorpay.cordova` version here or github URL. 
"com.razorpay.cordova": "^1.4.12",

## Xcode Version (iOS) :
Open Xcode > Go to `About Xcode` > copy the Xcode version here.
Version 12.0.1 (12A7300)

## Java and Gradle Version (android) :
Specify your Java and Gradle version.

### What you did:

I'm trying to build the iOS app using our existing Ionic Framework based app. It's working fine with the android app but throwing this error with Razorpay. We're using capacitor. 

I know you've mentioned that you don't support Capacitor, but why? How could you expect us to build two apps one using cordova and another using Capacitor? What's the point of using Capacitor then? 

It has to be fixed by your end or release a new version of the plugin with the support of Capacitor. We as a customer cannot rebuild the entire app. Please understand.

If you guys don't care about this problem, you might be losing many customers due to not fixing this. We might have to switch to something where it supports everything. 

And let me know what to do next? 

![Screenshot 2020-10-19 at 11 40 47 PM](https://user-images.githubusercontent.com/5548820/96496341-bc4c1900-1266-11eb-93c0-0226870e5aaa.png)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by imromec** [comment]
I've searched for all. If you think I've missed something to try, please let me know. Thank you.

**Comment by Nautiyalsachin** [comment]
Hey @imromec, can you share the razorpay-pod version here? You can find this inside your podfile.lock file.

**Comment by imromec** [comment]
It's 

`  - razorpay-pod (1.1.7)`

**Comment by imromec** [comment]
We need urgent support on this please help us fix this.

**Comment by Nautiyalsachin** [comment]
@imromec We have a sample app from where you can see the implementation 

https://github.com/razorpay/razorpay-cordova-sample-app/tree/master/rzp-cordova-example 

Try to run it locally and see if you are missing anything.

**Comment by imromec** [comment]
@Nautiyalsachin If you've read my description, I've clearly mentioned we're using Capacitor. What you're referring to me is a Cordova application. Please correct me if I've missed something.

**Comment by Nautiyalsachin** [comment]
Please create a feature request, which you can find in new issues > feature request. If we get more requests then we will consider working on it.

**Comment by imromec** [comment]
What do you mean by that? What do we do now? We already have 50 apps in Android running fine with Razorpay and now you're asking us to change it to Cordova because you cannot fix this?

**Comment by imromec** [comment]
Ionic will longer support Cordova in sometime. And instead of that, everyone has to switch to Capacitor and because of this we I don't think there is any point of using Razorpay with all our merchant apps.

**Comment by imromec** [comment]
It's an issue, not a feature request.

**Comment by krivri1989** [comment]
An arrogant Razorpay.
