### ISSUE TITLE
'Razorpay/Razorpay-Swift.h' file not found

### ISSUE THREAD

**Issue by imromec** [razorpay/razorpay-cordova#145]
## Description

Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest Razorpay Cordova plugin release to make sure your issue has not already been fixed. 

## Razorpay Package Version :
Open `Package.json`. > Copy `com.razorpay.cordova` version here or github URL. 
"com.razorpay.cordova": "^1.4.12",

## Xcode Version (iOS) :
Open Xcode > Go to `About Xcode` > copy the Xcode version here.
Version 12.0.1 (12A7300)

### What you did:

I'm trying to build the iOS app using our existing Ionic Framework based app. It's working fine with the android app but throwing this error with Razorpay. We're using capacitor. 

I know you've mentioned that you don't support Capacitor, but why? How could you expect us to build two apps one using cordova and another using Capacitor? What's the point of using Capacitor then? 

It has to be fixed by your end or release a new version of the plugin with the support of Capacitor. We as a customer cannot rebuild the entire app. Please understand.

If you guys don't care about this problem, you might be losing many customers due to not fixing this. We might have to switch to something where it supports everything. 

And let me know what to do next? 

![Screenshot 2020-10-19 at 11 40 47 PM](https://user-images.githubusercontent.com/5548820/96496341-bc4c1900-1266-11eb-93c0-0226870e5aaa.png)

### What happened:
In android, everything is working fine but there is an issue with iOS and we cannot build all the applications again in some other technology.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Make an Ionic Application
2. Run `ionic capacitor add ios`
3. Run `npm install com.razorpay.cordova`
4. Run `ionic capacitor build ios`
5. And build it from Xcode you'll see the error `'Razorpay/Razorpay-Swift.h' file not found`

### Suggested solution:
- Simply fix this `'Razorpay/Razorpay-Swift.h' file not found` in iOS and we're all good to go

**Comment by navneetnis1** [comment]
i am facing this issue too

**Comment by gurumukhi** [comment]
My Ionic project also uses Capacitor and this issue looks like a major road blocker for us too. Looking forward for an update on this.

**Comment by asharamseervi** [comment]
Thanking @imromec for raising this concern!

[Dependencies for iOS Development with capacitor](https://capacitorjs.com/docs/getting-started/dependencies#ios-development) seems reasonable to us, and they aren't seems to breaking anything with this package!

I'm asking, what's harm to add & cover more use cases? Someone should pick this and raise a pull request to get this merged into core!

**Comment by Virendra-Yadav** [comment]
I am also using Razorpay as payment method - uses Capacitor. I am unable to rollout the IOS version for payment module due to this.

I thought I was missing something but if it seems to be a issue after looking this chain - looking forward to get some help on this.

**Comment by Nautiyalsachin** [comment]
Hey @imromec can you share a sample app here, so that I can debug more on this issue ?

**Comment by imromec** [comment]
@Nautiyalsachin You could debug using these steps:


    Make an Ionic Application
    Run ionic capacitor add ios
    Run npm install com.razorpay.cordova
    Run ionic capacitor build ios
    And build it from Xcode you'll see the error 'Razorpay/Razorpay-Swift.h' file not found

Let me know if you need anything else.

**Comment by mic0108** [comment]
Im also facing this problem. It's working fine in android but in iOS it throws 'Razorpay/Razorpay-Swift.h' file not found error while building. It's a major roadblock. Please add capacitor support.

**Comment by Nautiyalsachin** [comment]
@imromec, are you using Cocoapods in your project? if yes, please share the razorpay-pod version here.

**Comment by iamromec** [comment]
@Nautiyalsachin Its `razorpay-pod (1.1.7)`

**Comment by iamromec** [comment]
@Nautiyalsachin Any update on this?

**Comment by iamromec** [comment]
Hey @Nautiyalsachin, how are we on this? I hope the permanent fix is being worked on. The solution we talked over the call is a temporary one, but we're expecting this to be fixed soon permanently.

**Comment by iamromec** [comment]
Hey @Nautiyalsachin, how are we on this? I hope the permanent fix is being worked on.

**Comment by abdulahad-07** [comment]
> Hey @Nautiyalsachin, how are we on this? I hope the permanent fix is being worked on. The solution we talked over the call is a temporary one, but we're expecting this to be fixed soon permanently.

What is a temporary solution? Can you please help with this?

**Comment by Nautiyalsachin** [comment]
@abdulahad-07, the temporary solution is to create the app using Cordova as we are giving Ionic support through Cordova and not directly to Ionic. For reference, you can see this [example](https://github.com/razorpay/razorpay-cordova-sample-app/tree/master/rzp-ionic-5-example).

Closing this issue now. Feel free to add comments or re-opening this issue.

**Comment by iamromec** [comment]
Why this issue has been closed without the fix? I thought Razorpay is a good developer friendly product.
