### ISSUE TITLE
Ionic Capacitor Integration

### ISSUE THREAD

**Issue by kdmalviyan** [razorpay/razorpay-cordova#147]
Hi Guys,
I am trying to integrate razorpay with Ionic-Capacitor project, but getting this issue when using browser for testing. And after payment success/failure it never calls callback.
![image](https://user-images.githubusercontent.com/5275882/97276252-f451ee00-185c-11eb-9754-2b5695694edb.png)
Same happened If I use emulator or real apk, it does not call callback functon.

Can someone help me with this please.

**Comment by Nautiyalsachin** [comment]
Closing this issue due to lack of information, please create a new issue with all the asked details.

**Comment by kdmalviyan** [comment]
@Nautiyalsachin I am not sure what more information you were expecting, can be more specific what exactly you want on this issue?

**Comment by sreerajkarippala** [comment]
same issue open a new issue #148
