### ISSUE TITLE
'Razorpay/Razorpay-Swift.h' file not found

### ISSUE THREAD

**Issue by iamromec** [razorpay/razorpay-cordova#149]
Duplicate of #

> ## Description
> 
> Please provide a clear and concise description of what the bug is. Include screenshots if needed.
> Please test using the latest Razorpay Cordova plugin release to make sure your issue has not already been fixed.
> ## Razorpay Package Version :
> 
> Open `Package.json`. > Copy `com.razorpay.cordova` version here or github URL.
> "com.razorpay.cordova": "^1.4.12",
> ## Xcode Version (iOS) :
> 
> Open Xcode > Go to `About Xcode` > copy the Xcode version here.
> Version 12.0.1 (12A7300)
> ### What you did:
> 
> I'm trying to build the iOS app using our existing Ionic Framework based app. It's working fine with the android app but throwing this error with Razorpay. We're using capacitor.
> 
> I know you've mentioned that you don't support Capacitor, but why? How could you expect us to build two apps one using cordova and another using Capacitor? What's the point of using Capacitor then?
> 
> It has to be fixed by your end or release a new version of the plugin with the support of Capacitor. We as a customer cannot rebuild the entire app. Please understand.
> 
> If you guys don't care about this problem, you might be losing many customers due to not fixing this. We might have to switch to something where it supports everything.
> 
> And let me know what to do next?
> 
> ![Screenshot 2020-10-19 at 11 40 47 PM](https://user-images.githubusercontent.com/5548820/96496341-bc4c1900-1266-11eb-93c0-0226870e5aaa.png)
> ### What happened:
> 
> In android, everything is working fine but there is an issue with iOS and we cannot build all the applications again in some other technology.
> ## Steps To Reproduce
> 
> Provide a detailed list of steps that reproduce the issue.
> 
>     1. Make an Ionic Application
> 
>     2. Run `ionic capacitor add ios`
> 
>     3. Run `npm install com.razorpay.cordova`
> 
>     4. Run `ionic capacitor build ios`
> 
>     5. And build it from Xcode you'll see the error `'Razorpay/Razorpay-Swift.h' file not found`
> 
> 
> ### Suggested solution:
> 
>     * Simply fix this `'Razorpay/Razorpay-Swift.h' file not found` in iOS and we're all good to go

**Comment by iamromec** [comment]
PLEASE DO NOT CLOSE WITHOUT THE PERMANENT FIX.

**Comment by iamromec** [comment]
If you've noticed #145, there are many developers who're facing the issue and you guys are hurry to close the issue without a permanent fix? Is it what Github for?

**Comment by hsarma** [comment]
I am also in need of capacitor support, unable to rollout the app just because of this issue.

**Comment by sparkidea-codecrab** [comment]
Facing the same issue.  When can we expect an answer on this?

**Comment by iamromec** [comment]
Razorpay Tech Team, We'd really appreciate it if you guys could help us out. Our business is being impacted due to this a lot! Please understand!

**Comment by sumedht** [comment]
@iamromec @hsarma @sparkidea-codecrab we have it in our roadmap for this year and we will update the thread when we make progress on this.

**Comment by deveshmishra34** [comment]
Any update on this ...I'm still facing this issue

**Comment by iamromec** [comment]
Hello Razorpay? It's already close to March! Will you care enough to update us on this?

**Comment by Nautiyalsachin** [comment]
Hi @iamromec, we are working on this, capacitor plugin is in development right now and very soon we will be releasing it officially. Please give us some time as we want to make sure that it should work on all platforms.

**Comment by kaurrJaspreet** [comment]
Any Update on same?
Actually, I am also totally stuck on this issue for last two weeks.
When are you planning to release the capacitor support?
Please update us on it, otherwise we plan to switch on any other payment method.
Anyone else can recommend any other payment method which can work for Ionic capacitor for android and ios

**Comment by sumedht** [comment]
@kaurrJaspreet We are in the last stage of the release of out capacitor plugin. It is expected to be released on 12th Mar. Apologies to make u wait for this.

**Comment by iamromec** [comment]
@sumedht Thanks. We are waiting for this. Please let us know when it goes live. Thanks, again.

**Comment by sumedht** [comment]
@kaurrJaspreet @iamromec We have updated plugin [here](https://github.com/razorpay/razorpay-capacitor/tree/plugin)

**Comment by iamromec** [comment]
@sumedht Thanks, but unable to install the new plugin. Please check the open issue [](https://github.com/razorpay/razorpay-capacitor/issues/2).
