### ISSUE TITLE
Company icon is not visible some time

### ISSUE THREAD

**Issue by vishnushelar** [razorpay/razorpay-cordova#15]
@akshaybhalotia 
Thanks for your support on previous bugs. I have got new issue. On android devices sometime company logo is not coming. Check attached screen shots. In first screen shot I can see logo in IOS device, but in second screen shot I can not see logo in android device.

![img-20160715-wa0027](https://cloud.githubusercontent.com/assets/5018918/16874961/254efffe-4aba-11e6-907b-8d1eedcdd619.jpg)

![screenshot_20160715-182258](https://cloud.githubusercontent.com/assets/5018918/16874973/3503cab0-4aba-11e6-8915-3419a49c8115.png)

**Comment by pronav** [comment]
Are you using `image` option or uploading logo from dashboard? If logo is not hosted on ssl enabled domain, some phones (e.g. Redmi) block it in webviews. It has nothing to do with Razorpay. I suggest you to remove hardcoded value and just upload it on dashboard.

**Comment by akshaybhalotia** [comment]
Or use base64 string, works in all cases :)

**Comment by selvagsz** [comment]
@vishnushelar check your [Content Security Policy ](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/#content-security-policy) as well. Closing this now. Feel free to reopen if you still face any issue

**Comment by anonrootkit** [comment]
using "image" from client, issue still persists.
