### ISSUE TITLE
Upgrade Android SDK `com.razorpay:checkout`

### ISSUE THREAD

**Issue by Himanshu-Mishr** [razorpay/razorpay-cordova#152]
### Description
I see `com.razorpay:checkout` is [hardcoded to `1.6.6`](https://github.com/razorpay/razorpay-cordova/blob/master/plugin.xml#L28). But new Android SDK updates are available on https://mvnrepository.com/artifact/com.razorpay/checkout. Can we upgrade repo to accommodate new fixes?

**Comment by vivekshindhe** [comment]
@Himanshu-Mishr Yes, we'll updating that in a few days. Thank you.

**Comment by sumedht** [comment]
@Himanshu-Mishr Updated to latest native version of SDK
