### ISSUE TITLE
Cordova Ionic 5.5 issues

### ISSUE THREAD

**Issue by ravimallya** [razorpay/razorpay-cordova#153]
## Description

I'm having strange issues while debugging in Android. I can see that the main activity is not getting reinitiated properly after successful payment and the checkoutActivity not killed, which results in inactivity of the mainActivity. We can't even get the activity in chrome devices to inspect. We have had to force stop the app to get this main activity reinitiated.

## Razorpay Package Version :
"com.razorpay.cordova": "github:razorpay/razorpay-cordova",

## Xcode Version (iOS) :
Open Xcode > Go to `About Xcode` > copy the Xcode version here.

## Java and Gradle Version (android) :
Java 8.281
Gradle 6.5

D:\GitRepos\xxx-app>ionic info

Ionic:
Ionic CLI : 6.16.3 (C:\Users\Ravi\AppData\Roaming\npm\node_modules@ionic\cli)
Ionic Framework : @ionic/angular 5.6.9
@angular-devkit/build-angular : 12.0.5
@angular-devkit/schematics : 12.0.5
@angular/cli : 12.0.5
@ionic/angular-toolkit : 4.0.0

Cordova:
Cordova CLI : 10.0.0
Cordova Platforms : 6.0.0, android 9.1.0, browser
Cordova Plugins : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 11 other plugins)

Utility:
cordova-res : 0.15.3
native-run : 1.4.0

System:
Android SDK Tools : 26.1.1 (C:\Users\Ravi\AppData\Local\Android\Sdk)
NodeJS : v14.17.0 (C:\Program Files\nodejs\node.exe)
npm : 7.17.0
OS : Windows 10

### What happened:

While going through the ADB log, I found some strange error. 
     
` W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
      I/ViewRootImpl@d5e8006[CheckoutActivity]: dispatchDetachedFromWindow
      D/InputTransport: Input channel destroyed: 'c213195', fd=187
      E/ActivityThread: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@a2ea7ba that was originally registered here. Are you missing a call to unregisterReceiver()?
          android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@a2ea7ba that was originally registered here. Are you missing a call to unregisterReceiver()?`

Check full error at:  https://pastebin.com/3serzBRL .

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a new ionic 5.5 app.
2. Initiate payment in testing mode using the below script after installing required plugins.
3. Build the app in ionic cli for android after adding the platform.
4. Open the android project in Android Studio. 
5. Add additional code for ionic Cordova files.
6. connect to a device and run.
7. Inspect the device in chrome devices.
8. Try to pay using any test methods. Here I've used UPI test@razorpay.
9. After successful payment, the app (mainActivity) is no longer accessible in chrome devices as it got disconnected.
10. We need to close and reopen the app to see the app in chrome devices.
11. Now we can see the com.razorpay.app in detached condition in chrome devices.

### Suggested solution:
1. After initiating the payment, need to freeze the mainActivity (app) or put in background.
2. Once the payment success or cancelled, get the mainACtivity into foreground and continue as before. 
3. Kill the com.razorpay.app instead of putting in detached mode.
4. 

## Code example, screenshot, or link to a repository:

    payWithRazorpay() {
      const _this = this;
      //  console.log(this.totalCost);
      const options = {
        description: 'Payment towards xxx interview booking',
        image: 'https://resources.xxxx.com/icon.png',
        currency: "INR", // your 3 letter currency code
        key: environment.razorPayId, // your Key Id from Razorpay dashboard
        amount: this.totalCost + '00', // Payment amount in smallest denomiation e.g. cents for USD
        name: 'xxxx',
        prefill: {
          email: '',
          contact: '',
          name: ''
        },
        theme: {
          color: '#F37254'
        },
        modal: {
          ondismiss: function () {
            // alert('dismissed')
          }
        }
      };
  
      var successCallback: any = (razorpay_payment_id) => {
        alert('payment_id: ' + razorpay_payment_id)

      if (_this.referralDeducted > 0) {
        _this.candidateData.applyReferral(this.userId, this.referralDeducted).then((resp: any) => {
        });
      }
      if (_this.couponCost > 0) {
        _this.candidateData.applyCoupon(this.userId, this.couponCode, this.couponCost).then((resp: any) => {
        });
      }
      _this.candidateData.finalizePayment(this.userId, this.totalCost, this.paymentId, razorpay_payment_id).then((resp: any) => {
          this.presentToast('info', 'Your payment is successfull.', 3000, 'top');
        this.navController.navigateForward('/candidate/booking/payment/success');
      //  _this.isPayment = false;
     //   console.log('is payment after success payment callback and finalize payment. ', this.isPayment);
      });
    }
      var cancelCallback: any = (error) => {
        alert(error.description + ' (Error ' + error.code + ')')
      }
      //RazorpayCheckout.on('payment.success', successCallback); // Not working somehow.
     // RazorpayCheckout.on('payment.cancel', cancelCallback) // Not working somehow.
      RazorpayCheckout.open(options,  successCallback, cancelCallback); // works. 
    }

See the comments for RazorpayCheckout.on() methods as well.

**Comment by vivekshindhe** [comment]
@ravimallya Hello, I would suggest you look into the example [repo]( https://github.com/razorpay/razorpay-cordova-sample-app/tree/master/rzp-ionic-5-example) for ionic 5. I'm pretty sure you're doubts will be cleared there directly.

**Comment by ravimallya** [comment]
I used the same repo and here's a sample app for your testing purposes.

**Comment by vivekshindhe** [comment]
@ravimallya We do not have any control over the android lifecycle at that point. The MainActivity you are referring to is from the User's application itself. We give back control. but nothing else. We also destroy our activity. Regarding the detached state. That is the cache and hence it shows that. Closing the ticket due to inactivity. Please feel free to comment here to reopen, or create another issue. Thank you.
