### ISSUE TITLE
Update to latest available Android SDK

### ISSUE THREAD

**Issue by Himanshu-Mishr** [razorpay/razorpay-cordova#154]
Hi @sumedht, I see a new version of Android SDK v1.6.14 is available, but the plugin is pointing to v1.6.10. 

We are interested in this feature : https://razorpay.com/docs/payments/payments/payment-methods/cards/google-pay/standard-integration/. I see from v1.6.12 has it. We cannot use it due to this restriction. 

Can we just go ahead if there is a `patch` update available, by adding this SDK from `./build-extras.gradle`? Or should we wait for this Cordova plugin to be updated?

```gradle
ext.postBuildExtras = {
    dependencies {  
        ...  
        implementation('com.razorpay:checkout:1.6.14')
    }
}
```

Ref: 
* https://razorpay.com/docs/payment-gateway/android-integration/standard/#list-of-razorpay-android-standard-sdk-versions-last
* https://mvnrepository.com/artifact/com.razorpay/checkout

**Comment by vivekshindhe** [comment]
@Himanshu-Mishr You can definitely go ahead with that. No issues, do update to version 1.6.15 for the same. Thank you. Closing the ticket now.
