### ISSUE TITLE
Wont build in Ios - Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by vanipriya** [razorpay/razorpay-cordova#18]
Hi,
I get the below errors while building for iOS : 
`Undefined symbols for architecture x86_64:
  "_SecRandomCopyBytes", referenced from:
      +[OTPSanta randomDataOfLength:] in Razorpay(OTPSanta.o)
  "_kSecRandomDefault", referenced from:
      +[OTPSanta randomDataOfLength:] in Razorpay(OTPSanta.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by vanipriya** [comment]
Fixed this by adding Security Framework to the build.

**Comment by Basavaraj-Tanikedar** [comment]
I'm getting same error in xcode 9.4, please anyone help me
