### ISSUE TITLE
Sample App on Ionic2 crashing with Message 'ReferenceError: RazorpayCheckout is not defined' 

### ISSUE THREAD

**Issue by ArunYogi** [razorpay/razorpay-cordova#25]
Hi Team,
I wanted to integrate RazorPay payment gateway in mobile application build in Ionic2. Inorder to get a feel how it would be, I tried the sample app in [sample app repo](https://github.com/razorpay/razorpay-cordova-sample-app) ,  under folder name '**rzp-ionic2-example**'.  I am getting below error

> ReferenceError: RazorpayCheckout is not defined

when I click pay button. Could you please clarify how to reference RazorpayCheckout class inside component for better integration, could you update the sample app as well.

**_Installation information:_**
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v7.2.0
Xcode version: Not installed

**Comment by selvagsz** [comment]
@ArunYogi Thanks for reporting the issue. Can you please provide some more information on how you installed & ran the app? Did you run the app on browser/android/ios platform ?

**Comment by ArunYogi** [comment]
I ran in chrome browser with command.

> $ ionic serve

Does environment make difference ?

**Comment by selvagsz** [comment]
Please check this https://github.com/razorpay/razorpay-cordova-sample-app/tree/master/rzp-ionic2-example#important-note. Let me know if that works

**Comment by selvagsz** [comment]
@ArunYogi This is not an issue with razorpay cordova plugin itself rather an issue with ionic-cli (https://github.com/driftyco/ionic-cli/issues/354) iteself. Closing this for now. Feel free to reopen/comment if I'm wrong

**Comment by ShaileshBhatNP** [comment]
Remember to add below lines to **_package.json_** file to clear the above bug

`"scripts": {`
   `"start": "ionic-app-scripts serve",`
    `"clean": "ionic-app-scripts clean",`
    `"build": "ionic-app-scripts build",`
    `"lint": "ionic-app-scripts lint",`
    `"ionic:build": "ionic-app-scripts build",`
    `"ionic:serve": "ionic-app-scripts serve --sourceMap source-map --iscordovaserve --wwwDir platforms/browser/www/ --buildDir platforms/browser/www/build"`
  `},`

**Comment by iThink32** [comment]
@ShaileshBhatNP thanks.
