### ISSUE TITLE
RazorpayCheckout.onResume(event) fails with method 'onResume' as being undefined

### ISSUE THREAD

**Issue by btdevn** [razorpay/razorpay-cordova#29]
When the cordova app resumes, as per the suggested code I am trying to bind the success and cancel functions and then pass the event object the razorpayCheckout object, and this is where it fails.

**Comment by mb-14** [comment]
@btdevn Please mail us the following details at support@razorpay.com :
- The version of our cordova plugin you are using
- Integration code
- Platform on which the error occurs

**Comment by akshaybhalotia** [comment]
This has been stagnant for a long time, hence closing. Please feel free to re-open for further discussion.
