### ISSUE TITLE
how to set order id in ionic to get which order has been payment

### ISSUE THREAD

**Issue by techashish12** [razorpay/razorpay-cordova#34]

**Comment by akshaybhalotia** [comment]
Do you want to send Order ID in the payment request, or do you want to check which order a particular payment was against?

**Comment by techashish12** [comment]
i want to check which order a particular payment was against / open cart 2.0 api

**Comment by akshaybhalotia** [comment]
@riagarg5 @mayankamencherla @ccrims0n Could you help here?

**Comment by techashish12** [comment]
actually i am using open cart 2.0 api in my project. when customer create the checkout an order id will be placed on the open cart backend and redirect to razorpay. Because there  are multiple user so i want to know that which open cart order id belongs to razor pay transaction.

**Comment by mayankamencherla** [comment]
@techashish12 If the admin clicks on the order in the opencart backend, he will see order details on the left hand side top corner of the page. Payment method is one of the details specified in this section.
