### ISSUE TITLE
how to use signature in ionic app

### ISSUE THREAD

**Issue by techashish12** [razorpay/razorpay-cordova#35]

**Comment by akshaybhalotia** [comment]
Signature is supposed to utilized by your backend. Please go through <https://docs.razorpay.com/v1/page/orders#verifying-signature> for more info.

**Comment by techashish12** [comment]
what in the main propose of signature it is for the payment done for the right customer (order-id)?
**i actually want to checksum for payment that the payment price in not alter via the user.is there is any way to check this.**

**Comment by akshaybhalotia** [comment]
Order ID contains information about the amount. Since order is created by your server to our server, user cannot change the price.
