### ISSUE TITLE
android  app is not able to list in playstore for some low end mobile phones ,because of 'android.permission.RECEIVE_SMS' permission

### ISSUE THREAD

**Issue by sk16** [razorpay/razorpay-cordova#36]
Hi 
Because of 'android.permission.RECEIVE_SMS' permission,  android  app is not able to list in playstore (even if minSDKVersion is equal or greater than specified in android app) for some low end mobile phones . Device name :Dell tab model no-venue 7 HSPA+

Error in play store : "your device is not compatible with this version"

**Comment by hariramsvnit** [comment]
@sk16 Can you please tell what is minSDKVersion of your app and device?

**Comment by sk16** [comment]
minSDKVersion of app : 19
Device android version: 4.4

After removing 'android.permission.RECEIVE_SMS' , Device's playstore app was able to search and install the app.

**Comment by hariramsvnit** [comment]
@sk16 The tab(device) doesn't have sim slots?

**Comment by sk16** [comment]
yes it has sim slots.

**Comment by sk16** [comment]
this was happening on that particular device.

**Comment by hariramsvnit** [comment]
Okay, maybe this issue is related to that specific device. We also have a sample app(https://play.google.com/store/apps/details?id=com.razorpay.sampleapp&hl=en) on play store. You may try to install that on your device and see if you are able to install it or not?

**Comment by sk16** [comment]
We don't have that device . The device was of one of our client's student.

**Comment by hariramsvnit** [comment]
@sk16 Okay, it looks like a device related issue, closing the issue for now. Feel free to reopen if you face the similar issue again.
