### ISSUE TITLE
success callback event not working

### ISSUE THREAD

**Issue by maheshkumargp** [razorpay/razorpay-cordova#37]
Hi,
i'm trying to make a service call on success callback of razorpay but it is not working.
here is the code 
           var successCallback = function (payment_id) {
           // alert('payment_id: ' + payment_id);
            PurchaseService.post({}, function (resp) {
              LocalStorage.set('songs', resp);
              Helper.storeNotes();
              $scope.cartSongs = CartService.getAll({}, function (resp) {
                $rootScope.badgeNumber = resp.size;
                $rootScope.activeTab = 'Purchased'
                $state.go('app.playlists', null, { reload: true, notify: true });
              });
            });
          }

          var cancelCallback = function (error) {
            alert(error.description + ' (Error ' + error.code + ')')
          };

          RazorpayCheckout.on('payment.success', successCallback);
          RazorpayCheckout.on('payment.cancel', cancelCallback);
          //RazorpayCheckout.on('payment.external_wallet', successCallback)
          RazorpayCheckout.open(options);

          document.addEventListener('resume', onResume, false);
          var onResume = function (event) {
            // Re-register the payment success and cancel callbacks
            RazorpayCheckout.on('payment.success', successCallback)
            RazorpayCheckout.on('payment.cancel', cancelCallback)
            // Pass on the event to RazorpayCheckout
            RazorpayCheckout.onResume(event);
          };

**Comment by akshaybhalotia** [comment]
@maheshkumargp You are mixing 2 flows. What you are trying to achieve here is https://github.com/razorpay/razorpay-cordova#legacy but the code snippet is from https://github.com/razorpay/razorpay-cordova#orders-api-flow. Please go through the README again and read about Orders API flow as mentioned.
