### ISSUE TITLE
Unable to build for iOS after adding the plugin in a new ionic 3 app

### ISSUE THREAD

**Issue by subhg** [razorpay/razorpay-cordova#38]
Hi there,

I am new to Ionic and we have a requirement to add payment gateway to our app where I chose Razorpay as it was easy to integrate. It works fine when running on browser but when I tried to build it for iOS it is giving the following error:

An error occurred while running cordova build ios (exit code 1):
        
        (truncated) ...  -fmodules-prune-interval=86400 -fmodules-prune-after=345600
        -fbuild-session-file=/Users/subhankar/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation
        -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers
        -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match
        -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter
        -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow
        -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion
        -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match
        -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot
        /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk
        -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=9.0 -g
        -fvisibility=hidden -Wno-sign-conversion -Wno-infinite-recursion -fobjc-abi-version=2 -fobjc-legacy-dispatch
        -iquote
        /Users/subhankar/Library/Developer/Xcode/DerivedData/ParkYouGo-dhqtmfcpjgriiidfrttcynaeksxz/Build/Intermediates/ParkYouGo.build/Debug-iphonesimulator/ParkYouGo.build/ParkYouGo-generated-files.hmap
        -I/Users/subhankar/Library/Developer/Xcode/DerivedData/ParkYouGo-dhqtmfcpjgriiidfrttcynaeksxz/Build/Intermediates/ParkYouGo.build/Debug-iphonesimulator/ParkYouGo.build/ParkYouGo-own-target-headers.hmap
        -I/Users/subhankar/Library/Developer/Xcode/DerivedData/ParkYouGo-dhqtmfcpjgriiidfrttcynaeksxz/Build/Intermediates/ParkYouGo.build/Debug-iphonesimulator/ParkYouGo.build/ParkYouGo-all-target-headers.hmap
        -iquote
        /Users/subhankar/Library/Developer/Xcode/DerivedData/ParkYouGo-dhqtmfcpjgriiidfrttcynaeksxz/Build/Intermediates/ParkYouGo.build/Debug-iphonesimulator/ParkYouGo.build/ParkYouGo-project-headers.hmap
        -I/Users/subhankar/parkyougo/pygHybridApp/platforms/ios/build/emulator/include
        -I/Users/subhankar/parkyougo/pygHybridApp/platforms/ios/build/emulator/usr/local/lib/include
        -I/Users/subhankar/Library/Developer/Xcode/DerivedData/ParkYouGo-dhqtmfcpjgriiidfrttcynaeksxz/Build/Intermediates/UninstalledProducts/include
        -I/Users/subhankar/Library/Developer/Xcode/DerivedData/ParkYouGo-dhqtmfcpjgriiidfrttcynaeksxz/Build/Intermediates/UninstalledProducts/iphonesimulator/include
        -I/Users/subhankar/parkyougo/pygHybridApp/platforms/ios/build/emulator
        -I/Users/subhankar/Library/Developer/Xcode/DerivedData/ParkYouGo-dhqtmfcpjgriiidfrttcynaeksxz/Build/Intermediates/ParkYouGo.build/Debug-iphonesimulator/ParkYouGo.build/DerivedSources/x86_64
        -I/Users/subhankar/Library/Developer/Xcode/DerivedData/ParkYouGo-dhqtmfcpjgriiidfrttcynaeksxz/Build/Intermediates/ParkYouGo.build/Debug-iphonesimulator/ParkYouGo.build/DerivedSources
        -F/Users/subhankar/parkyougo/pygHybridApp/platforms/ios/build/emulator -FParkYouGo/Plugins/com.googlemaps.ios
        -FParkYouGo/Plugins/com.razorpay.cordova -FParkYouGo/Plugins/cordova-plugin-facebook4 -include
        /Users/subhankar/parkyougo/pygHybridApp/platforms/ios/build/sharedpch/ParkYouGo-Prefix-eyboyhaabhkgzjbmjchhhqxzsuay/ParkYouGo-Prefix.pch
        -MMD -MT dependencies -MF
        /Users/subhankar/Library/Developer/Xcode/DerivedData/ParkYouGo-dhqtmfcpjgriiidfrttcynaeksxz/Build/Intermediates/ParkYouGo.build/Debug-iphonesimulator/ParkYouGo.build/Objects-normal/x86_64/GoogleMapsViewController.d
        --serialize-diagnostics
        /Users/subhankar/Library/Developer/Xcode/DerivedData/ParkYouGo-dhqtmfcpjgriiidfrttcynaeksxz/Build/Intermediates/ParkYouGo.build/Debug-iphonesimulator/ParkYouGo.build/Objects-normal/x86_64/GoogleMapsViewController.dia
        -c
        /Users/subhankar/parkyougo/pygHybridApp/platforms/ios/ParkYouGo/Plugins/cordova-plugin-googlemaps/GoogleMapsViewController.m
        -o
        /Users/subhankar/Library/Developer/Xcode/DerivedData/ParkYouGo-dhqtmfcpjgriiidfrttcynaeksxz/Build/Intermediates/ParkYouGo.build/Debug-iphonesimulator/ParkYouGo.build/Objects-normal/x86_64/GoogleMapsViewController.o
        
        ** BUILD FAILED **
        
        
        The following build commands failed:
        CompileC
        /Users/subhankar/Library/Developer/Xcode/DerivedData/ParkYouGo-dhqtmfcpjgriiidfrttcynaeksxz/Build/Intermediates/ParkYouGo.build/Debug-iphonesimulator/ParkYouGo.build/Objects-normal/x86_64/Main-8487F6F6E387796A.o
        ParkYouGo/Plugins/com.razorpay.cordova/Razorpay/Main.m normal x86_64 objective-c
        com.apple.compilers.llvm.clang.1_0.compiler
        (1 failure)
        Error: Error code 65 for command: xcodebuild with args:
        -xcconfig,/Users/subhankar/parkyougo/pygHybridApp/platforms/ios/cordova/build-debug.xcconfig,-workspace,ParkYouGo.xcworkspace,-scheme,ParkYouGo,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS
        Simulator,name=iPhone
        SE,build,CONFIGURATION_BUILD_DIR=/Users/subhankar/parkyougo/pygHybridApp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/subhankar/parkyougo/pygHybridApp/platforms/ios/build/sharedpch

Kindly help.
Thanks

**Comment by akshaybhalotia** [comment]
@subhg this error is not related to our plugin, this is related to the provisioning profiles and certificates installed on your system ([reference](https://stackoverflow.com/questions/34166175/cordova-run-with-ios-error-error-code-65-for-command-xcodebuild-with-args)). Please make a Google or Stackoverflow search with this error code and you'll see a lot of suggestions / fixes for this.

**Comment by subhg** [comment]
Hi Akshay,

The provisioning profile has already been set and it was building all fine until I added the plugin. Here's the message:

** BUILD FAILED **
        
        
        The following build commands failed:
        CompileC
        /Users/subhankar/Library/Developer/Xcode/DerivedData/ParkYouGo-dhqtmfcpjgriiidfrttcynaeksxz/Build/Intermediates/ParkYouGo.build/Debug-iphonesimulator/ParkYouGo.build/Objects-normal/x86_64/Main-B3CD61F543D011DC.o
        ParkYouGo/Plugins/com.razorpay.cordova/Razorpay/Main.m normal x86_64 objective-c
        com.apple.compilers.llvm.clang.1_0.compiler
        (1 failure)
        Error: Error code 65 for command: xcodebuild with args:
        -xcconfig,/Users/subhankar/parkyougo/pygHybridApp/platforms/ios/cordova/build-debug.xcconfig,-workspace,ParkYouGo.xcworkspace,-scheme,ParkYouGo,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS
        Simulator,name=iPhone
        SE,build,CONFIGURATION_BUILD_DIR=/Users/subhankar/parkyougo/pygHybridApp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/subhankar/parkyougo/pygHybridApp/platforms/ios/build/sharedpch

Kindly check.
Thanks

**Comment by akshaybhalotia** [comment]
Can you try cleaning the project and derived data, then build again?

**Comment by subhg** [comment]
I tried just now but the same issue. Is it due to Ionic version?

ionic info output:

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v6.9.5
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : not installed
    npm        : 3.10.10

Can it be due to Objective C vs Swift compatibility?

**Comment by akshaybhalotia** [comment]
I don't think it could be due to that. Could you please run our Ionic 3 sample app once from [razorpay/razorpay-cordova-sample-app](https://github.com/razorpay/razorpay-cordova-sample-app) once and report issues?

**Comment by pkurimella** [comment]
@akshaybhalotia I was able to reproduce the same error with ionic 1 sample.

```
The following build commands failed:
        CompileC /Users/dcrln/Library/Developer/Xcode/DerivedData/rzp-ionic1-example-btsvzkeecsersmcsklplzsuehixj/Build/Intermediates/rzp-ionic1-example.build/Debug-iphonesimulator/rzp-ionic1-example.build/Objects-normal/x86_64/Main-6C0A4A11C81695A9.o rzp-ionic1-example/Plugins/com.razorpay.cordova/Razorpay/Main.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/dcrln/prototypes/razorpay-cordova-sample-app/rzp-ionic1-example/platforms/ios/cordova/build-debug.xcconfig,-workspace,rzp-ionic1-example.xcworkspace,-scheme,rzp-ionic1-example,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone SE,build,CONFIGURATION_BUILD_DIR=/Users/dcrln/prototypes/razorpay-cordova-sample-app/rzp-ionic1-example/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/dcrln/prototypes/razorpay-cordova-sample-app/rzp-ionic1-example/platforms/ios/build/sharedpch
```

System

>  Android SDK Tools : 25.2.5
    Node              : v6.11.0
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b
    ios-deploy        : 1.9.1
    ios-sim           : 6.0.0
    npm               : 3.10.10
    cordova        :7.0.1

**Comment by akshaybhalotia** [comment]
@pkurimella We are unable to reproduce this scenario.

Also, does Ionic 3 sample work fine in your case? I ask this because earlier you had raised an issue involving Ionic 3. This could have resulted due to differences in different Ionic and Cordova versions.

**Comment by akshaybhalotia** [comment]
Also, please try some suggestions listed here: https://forum.ionicframework.com/t/ionic-build-ios-plugin-errors-exit-code-65/7274

**Comment by deveshmishra34** [comment]
I was also facing this issue after installing razor pay. But i resolve it just by setting deployment target 10.0. Hope this will work for you as well.
Thank you

**Comment by rajnishp** [comment]
Hi, 
Stuck here , Any help would be appreciated

Ionic Info output :

`Ionic CLI                     : 5.4.16 (/opt/homebrew/lib/node_modules/ionic)
   Ionic Framework        : @ionic/angular 5.6.10
   @angular-devkit/build-angular : 0.803.29
   @angular-devkit/schematics    : 8.3.29
   @angular/cli                : 8.3.29
   @ionic/angular-toolkit        : 2.3.3`  

Cordova:

   `Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.1.0, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 27 other plugins)`

Utility:

   `cordova-res (update available: 0.15.3) : 0.11.0
   native-run                             : 1.4.0`

System:

   `ios-sim : 8.0.2
   NodeJS  : v16.4.2 (/opt/homebrew/Cellar/node/16.4.2/bin/node)
   npm     : 6.14.13
   OS      : macOS Big Sur
   Xcode   : Xcode 12.5.1 Build version 12E507
`
   
   
[cordova] ** BUILD FAILED **
[cordova]
[cordova]
[cordova] The following build commands failed:
[cordova] 	CompileC /var/root/Library/Developer/Xcode/DerivedData/Googly-bgehilzmrsqtoafctkykfzrcycrd/Build/Intermediates.noindex/Googly.build/Debug-iphonesimulator/Googly.build/Objects-normal/arm64/Main-a403959957dc0ddf1f992f30f463629baec530ed2d3dadb7c7135a13ad876858.o /Users/rajnishp/cuttingEdge/mogiio-ionic-apps/ott/platforms/ios/Googly/Plugins/com.razorpay.cordova/Main.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[cordova] (1 failure)
[cordova] xcodebuild: Command failed with exit code 65

**Comment by vivekshindhe** [comment]
@rajnishp Try deleting the derived data folder.

**Comment by rajnishp** [comment]
Hi, 
In my case deriveddata location is as below
`~/Library/Developer/Xcode/DerivedData`

Even after deleting it results in same error as above. 

After running command `ionic cordova build ios` it again generating `DerivedData` folder

I cloned from repo [https://github.com/razorpay/razorpay-cordova-sample-app.git](url)  and try to run `rzp-ionic-5-example` in M1 chip mac,

**Comment by rajnishp** [comment]
Hi, 
In my case deriveddata location is as below
`~/Library/Developer/Xcode/DerivedData`

Even after deleting it results in same error as above. 

After running command `ionic cordova build ios` it again generating `DerivedData` folder

I cloned from repo [https://github.com/razorpay/razorpay-cordova-sample-app.git](url)  and try to run `rzp-ionic-5-example` in M1 chip mac,
