### ISSUE TITLE
Losing control over the Ionic3 component after successful payment

### ISSUE THREAD

**Issue by Dineshrajaa** [razorpay/razorpay-cordova#42]
Hi everyone,

 Thanks for making this awesome plugin, I am developing an Ionic3 app and I have added Razorpay plugin
everything is fine(I could get the paymentID on successful transaction) but the problem is I need to verify the payment by hitting one endpoint but that is not happening, is this because of lose of control over the class??

Any help would be much appreciated!

**Comment by LogicSquareTech** [comment]
Me too, facing the same problem. 
Is anyone at RazorPay looking into it ?

**Comment by hariramsvnit** [comment]
@Dineshrajaa Are you talking about the cases where Cordova/Ionic activity get destroyed by the android system?

**Comment by Dineshrajaa** [comment]
@hariramsvnit yeah I thought the issue was something like that but with help of selva I found that issue is with callback scope so binding the success callback like this 

> successCallback.bind(this)

I was able to resolve this issue..
so I am closing this issue, thanks for your support @selvagsz  and @hariramsvnit

**Comment by krngd2** [comment]
What is the issue with callback scope ? How to solve this?

**Comment by hariramsvnit** [comment]
@krngd2 If you want to call any method from the callback function, then you need to bind the callback with the class which contains that method. You can do it, like this
`successCallback.bind(this)`
