### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by devxenno** [razorpay/razorpay-cordova#43]
$ cordova plugin add http://github.com/razorpay/razorpay-cordova.git --save
Error: Failed to fetch plugin http://github.com/razorpay/razorpay-cordova.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! git clone --template=C:\Users\Xenno\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@g                                                                                                                                                            ithub.com/razorpay/razorpay-cordova.git C:\Users\Xenno\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-co                                                                                                                                                            m-razorpay-razorpay-cordova-git-041764d0: Cloning into bare repository 'C:\Users\Xenno\AppData\Roaming\npm-cache\_g                                                                                                                                                            it-remotes\git-ssh-git-github-com-razorpay-razorpay-cordova-git-041764d0'...
npm ERR! git clone --template=C:\Users\Xenno\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@g                                                                                                                                                            ithub.com/razorpay/razorpay-cordova.git C:\Users\Xenno\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-co                                                                                                                                                            m-razorpay-razorpay-cordova-git-041764d0: Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list                                                                                                                                                             of known hosts.
npm ERR! git clone --template=C:\Users\Xenno\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@g                                                                                                                                                            ithub.com/razorpay/razorpay-cordova.git C:\Users\Xenno\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-co                                                                                                                                                            m-razorpay-razorpay-cordova-git-041764d0: Permission denied (publickey).
npm ERR! git clone --template=C:\Users\Xenno\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@g                                                                                                                                                            ithub.com/razorpay/razorpay-cordova.git C:\Users\Xenno\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-co                                                                                                                                                            m-razorpay-razorpay-cordova-git-041764d0: fatal: Could not read from remote repository.
npm ERR! git clone --template=C:\Users\Xenno\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@g                                                                                                                                                            ithub.com/razorpay/razorpay-cordova.git C:\Users\Xenno\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-co                                                                                                                                                            m-razorpay-razorpay-cordova-git-041764d0:
npm ERR! git clone --template=C:\Users\Xenno\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@g                                                                                                                                                            ithub.com/razorpay/razorpay-cordova.git C:\Users\Xenno\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-co                                                                                                                                                            m-razorpay-razorpay-cordova-git-041764d0: Please make sure you have the correct access rights
npm ERR! git clone --template=C:\Users\Xenno\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@g                                                                                                                                                            ithub.com/razorpay/razorpay-cordova.git C:\Users\Xenno\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-co                                                                                                                                                            m-razorpay-razorpay-cordova-git-041764d0: and the repository exists.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"                                                                                                                                                             "install" "http://github.com/razorpay/razorpay-cordova.git" "--save"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\xxx\AppData\Roaming\npm-cache\_git-                                                                                                                                                            remotes\_templates --mirror ssh://git@github.com/razorpay/razorpay-cordova.git C:\Users\xxx\AppData\Roaming\npm-c                                                                                                                                                            ache\_git-remotes\git-ssh-git-github-com-razorpay-razorpay-cordova-git-041764d0
npm ERR! Cloning into bare repository 'C:\Users\Xenno\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-com                                                                                                                                                            -razorpay-razorpay-cordova-git-041764d0'...
npm ERR! Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Bitnami\wampstack-5.6.31-0\apache2\htdocs\mobile\node_modules\npm-debug.log

**Comment by AnupNair91** [comment]
try `cordova plugin add com.razorpay.cordova --nofetch`
it worked for me.

**Comment by hariramsvnit** [comment]
Please refer the usages section for windows machine(https://github.com/razorpay/razorpay-cordova#usage).
