### ISSUE TITLE
Razorpay subscription payment support

### ISSUE THREAD

**Issue by Rinkuk1993** [razorpay/razorpay-cordova#45]
Razorpay has recently launched [Subscription based payment](https://razorpay.com/subscriptions/#developers) 

This option is not available in cordova plugin. Can someone please help to add the feature to plugin?

**Comment by Mayur-Wadpalliwar** [comment]
@Rinkuk1993 Our subscriptions APIs needs to be called from a backend server and not from the frontend. Hence the same could not be integrated in Cordova.

You may refer out detailed documentation on subscriptions here: https://razorpay.com/docs/subscriptions/

**Comment by pronav** [comment]
Moreover, you should be able to pass `subscription_id` in `options` just link any other SDK.
