### ISSUE TITLE
iOS Build error - 'Razorpay/Razorpay.h' file not found

### ISSUE THREAD

**Issue by RameshkrishnanV** [razorpay/razorpay-cordova#46]
fatal error: 'Razorpay/Razorpay.h' file not found
#import <Razorpay/Razorpay.h>

This is the error i'm getting when building for ios

**Comment by AbhinavArora95** [comment]
There must be some integration error at your end. Kindly refer to our sample app - https://github.com/razorpay/razorpay-cordova-sample-app.
