### ISSUE TITLE
Unhandled promise rejection (rejection id: 1): CordovaError: Failed to fetch plugin com.razorpay.cordova via registry

### ISSUE THREAD

**Issue by kanji-keraliya** [razorpay/razorpay-cordova#48]
`(node:19384) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Failed to fetch plugin com.razorpay.cordova via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
'sh' is not recognized as an internal or external command,
operable program or batch file.
npm WARN @ionic-native/app-version@3.12.1 requires a peer of @ionic-native/core@^3.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/firebase-analytics@3.12.1 requires a peer of @ionic-native/core@^3.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/intercom@3.12.1 requires a peer of @ionic-native/core@^3.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/network@3.12.1 requires a peer of @ionic-native/core@^3.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/social-sharing@3.12.1 requires a peer of @ionic-native/core@^3.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngx-translate/http-loader@0.0.3 requires a peer of @ngx-translate/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! com.razorpay.cordova@1.3.1 postinstall: `sh scripts/download_ios_framework.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the com.razorpay.cordova@1.3.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2017-12-23T08_11_42_730Z-debug.log
(node:19384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by kanji-keraliya** [comment]
Does anyone maintain this git or not?

**Comment by pronav** [comment]
what was the command that you issued?

**Comment by pronav** [comment]
Are you using windows? I think post-install script fails because `sh` executable is not found on your system. That is used to download ios related files necessary for plugin to function. I suppose we can skip that part for windows. We'll update once that's done.

**Comment by kanji-keraliya** [comment]
I am using windows 10
I need it for android

I tried both one
cordova plugin add com.razorpay.cordova --save
and 
ionic cordova plugin add com.razorpay.cordova --save

**Comment by AnthonyKot** [comment]
Hello. The same issue here, any updates?

**Comment by pronav** [comment]
@AnthonyKot this has been fixed. If you still face the same error, please run it in [git shell](https://git-scm.com/downloads) instead of `cmd`
