### ISSUE TITLE
Using Order Api not getting "signature" in return after Success

### ISSUE THREAD

**Issue by Foxbelly** [razorpay/razorpay-cordova#49]
I am using Test mode of Integration. I am passing order_id in the options but not getting signature to verify after success callback.

**Comment by hariramsvnit** [comment]
Please go through the Orders API doc(https://docs.razorpay.com/page/orders#section-checkout-on-android), you need to implement `PaymentResultWithDataListener` interface for receiving signature.

**Comment by Foxbelly** [comment]
Hi,
I am using cordova not native Andriod. So kindly provide the solution for the Cordova SDK.

**Comment by hariramsvnit** [comment]
In case of Cordova, if you are passing `order_id` then it will return signature also. Can you log the response you are receiving and provide it to me to cross check?

**Comment by Foxbelly** [comment]
Hi,
I am passing payment_capture: 1 at the time of creating the order and passing order_id at the time of payment. But in the success callback i am receiving response as pay_***** but not a json with the signature.

**Comment by hariramsvnit** [comment]
Can you please conform the platform? ios, android or browser?

**Comment by Foxbelly** [comment]
Hi,
Platform is Android but not native. I am using Ionic framework which uses Cordova. I have implemented the call as mentioned in the README.
