### ISSUE TITLE
npm install error for ios

### ISSUE THREAD

**Issue by suvajit** [razorpay/razorpay-cordova#51]
Node version : 9.3.0_1
Receive following error on npm install on my Ionic project : 
LII-RLM-013:moblit-application suvajit$ npm install 

> com.razorpay.cordova@1.3.2 postinstall /Users/suvajit/Works/Ionic/moblit-ios/moblit-application/node_modules/com.razorpay.cordova
> sh scripts/download_ios_framework.sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   314  100   314    0     0    990      0 --:--:-- --:--:-- --:--:--  3609
Archive:  ./Razorpay.framework-0.15.1.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./Razorpay.framework-0.15.1.zip or
        ./Razorpay.framework-0.15.1.zip.zip, and cannot find ./Razorpay.framework-0.15.1.zip.ZIP, period.
cp: ./Razorpay.framework: No such file or directory
npm WARN @ionic-native/android-permissions@4.5.2 requires a peer of @ionic-native/core@^4.2.0 but none was installed.
npm WARN @ionic-native/background-geolocation@4.5.2 requires a peer of @ionic-native/core@^4.2.0 but none was installed.
npm WARN @ionic-native/screenshot@4.5.2 requires a peer of @ionic-native/core@^4.2.0 but none was installed.
npm WARN @ionic-native/social-sharing@4.5.2 requires a peer of @ionic-native/core@^4.2.0 but none was installed.
npm ERR! Darwin 17.2.0
npm ERR! argv "/usr/local/Cellar/node@6/6.9.5/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! com.razorpay.cordova@1.3.2 postinstall: `sh scripts/download_ios_framework.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the com.razorpay.cordova@1.3.2 postinstall script 'sh scripts/download_ios_framework.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the com.razorpay.cordova package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     sh scripts/download_ios_framework.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs com.razorpay.cordova
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls com.razorpay.cordova
npm ERR! There is likely additional logging output above.

I recently upgraded my node version from 7.x to 9.x and received this error.
Please advice.

**Comment by AbhinavArora95** [comment]
Hi, the link had an issue. Apologies for the inconvenience. Now it shall be working.
