### ISSUE TITLE
Issue while calling - RazorpayCheckout is not defined (Min SDK Ver. -19 issue)

### ISSUE THREAD

**Issue by warlockdn** [razorpay/razorpay-cordova#73]
* **Common to Both platforms :-**

  - [x] I have gone through the README(https://github.com/razorpay/razorpay-cordova)
  - [x] I have searched for a similar issue (https://github.com/razorpay/razorpay-cordova/issues)
  - [x] I am using the latest version of our framework (https://github.com/razorpay/razorpay-cordova/releases)
  - [x] I have cleaned my project.

First of all while creating a build I received a issue to update the min-sdk version to 16. Please find error below

```
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [com.razorpay:checkout:1.4.8] /home/warlock/.gradle/caches/transforms-1/files-1.1/checkout-1.4.8.aar/39ae926e4bb4726ecc59f8d09614137a/AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 19,
  		or use tools:overrideLibrary="com.razorpay" to force usage (may lead to runtime failures)
```
So, I updated the min-sdk to 19. Then I started receiving the following error even though I had already declared Razorpay in declarations.d.ts

Please look into this issue I am stuck with this. I cannot proceed further.

## IDE Specs
Gradle 5.0
Latest Plugin Version

**Comment by warlockdn** [comment]
Can your plugin be updated to use updated sdk of v19 ?

**Comment by hariramsvnit** [comment]
@warlockdn We have updated min SDK version to 19 in our SDK, your app's min SDK version is 16, so you are facing this error. Please update min SDK version in your app to 19.
