### ISSUE TITLE
Uncaught DOMException: Blocked a frame with origin "https://api.razorpay.com" from accessing a cross-origin frame

### ISSUE THREAD

**Issue by diksha-94** [razorpay/razorpay-cordova#87]
I am facing **Uncaught DOMException: Blocked a frame with origin "https://api.razorpay.com" from accessing a cross-origin frame in cordova android app**.
I have gone through the README(https://github.com/razorpay/razorpay-cordova)
Installed plugin **com.razorpay.cordova** .

Content-Security-Policy in my app is
<meta http-equiv="Content-Security-Policy" content="default-src * 'self' data: gap: https://ssl.gstatic.com 'unsafe-inline' 'unsafe-eval' https://*.razorpay.com; style-src 'self' 'unsafe-inline'; media-src *">

When trying to make the payment through Razorpay, can see the modal opening for payment, but clicking on Pay doesn't work. It blocks the iframe.

**Comment by iThink32** [comment]
please update to our latest version and reopen this issue if it the problem persists.
