### ISSUE TITLE
Getting dyld: Symbol not found: __T0BOWV on integrating razorpay cordova sdk in Xcode 10

### ISSUE THREAD

**Issue by neha3018** [razorpay/razorpay-cordova#88]
I am getting Error  `dyld: Symbol not found: __T0BOWV`
Referenced from: /private/var/containers/Bundle/Application/7C864AAE-DDC5-4F4D-9982-CA047BC0ECDF/App.app/Frameworks/Razorpay.framework/Razorpay
Expected in: /private/var/containers/Bundle/Application/7C864AAE-DDC5-4F4D-9982-CA047BC0ECDF/App.app/Frameworks/libswiftCore.dylib
in /private/var/containers/Bundle/Application/7C864AAE-DDC5-4F4D-9982-CA047BC0ECDF/App.app/Frameworks/Razorpay.framework/Razorpay
(lldb)

My app is getting crashed on running in device with the given error.

I included the plugin with command `cordova plugin add com.razorpay.cordova --save`

My Xcode version is 10 and Swift 4.2. Also I have set Always Embed Swift Standard Libraries of your main target to yes.

Also I have added the line

`#import <Razorpay/Razorpay-Swift.h>`
to the top of my Main.m file

But none of above worked for me. Whats wrong I am doing here? Thanks in advance.

**Comment by neha3018** [comment]
Any help please?

**Comment by iThink32** [comment]
@neha3018 add razorpay framework to embedded libraries section along with linked libraries

**Comment by neha3018** [comment]
@iThink32 I had already added razorpay framework to embedded libraries and watched your integration videos....
I had done all the steps and searching for resolutions till now. But none work for me.

**Comment by neha3018** [comment]
Yes, I am using the latest framework version only. I had also used the previous versions which was working fine and there were no such issue. But for some other project I am using the latest framework, which is giving this error.

**Comment by iThink32** [comment]
@neha3018 ok , can you give me you Skype id so that we can have a Skype call tomorrow?
