### ISSUE TITLE
android.permission.RECEIVE_SMS

### ISSUE THREAD

**Issue by pkumar-uk** [razorpay/razorpay-cordova#89]
Google is restricting which apps can request Call Log and SMS permissions. And Razorpay plugin is having android.permission.RECEIVE_SMS.
Will the plugin work if this is removed.
Please advice if you are changing plugin to adhere to Google policy or if thee are work arounds

**Comment by sumedht** [comment]
After removing permission it will not auto read SMS on the transaction.
We are updating our plugin according to Google Play policy and will roll-out an update before this month end.

**Comment by pkumar-uk** [comment]
Any Updates?

**Comment by sumedht** [comment]
@pkumar-uk we have updated android-sdk and will update for cordova in next 2-3 days.

**Comment by sumedht** [comment]
@pkumar-uk Updated in v1.4.0 n it's published now.

**Comment by abhilashWipadika** [comment]
Google is restricting which apps can request Call Log and SMS permissions. And Razorpay plugin is having android.permission.RECEIVE_SMS.
Will the plugin work if this is removed.
Please advice if you are changing the plugin to adhere to Google policy or if thee are workarounds

**Comment by sumedht** [comment]
@abhilashWipadika We have removed SMS permission and it's released it in v1.4.0 itself. U can use the latest SDK version.

**Comment by TheCodeWork-dev** [comment]
Google is still preventing it even if I'm using latest SDK. Any suggestions?

**Comment by TitikshaDaga** [comment]
This permission is still getting added :  <uses-permission android:name="android.permission.RECEIVE_SMS" /> after building the application.

**Comment by pkumar-uk** [comment]
I can confirm. For me it was working and SMS permission was removed and google accepted my  apk.

**Comment by TitikshaDaga** [comment]
ok. There might be an issue with some other plugin then.

**Comment by vibinflogesoft** [comment]
Iam facing the same issue with razorpay version1.4.1 ,my app rejected with error
Based on our review, we found your app’s expressed user experience did not match your declared core functionality {SMS-based financial transactions (e.g., 5 digit messages), and related activity including OTP account verification for financial transactions and fraud detection}. Please remove these permissions from your app.
Any Solution?
