### ISSUE TITLE
Not able to add the plugin for iOS

### ISSUE THREAD

**Issue by nssundar** [razorpay/razorpay-cordova#90]
* **Common to Both platforms :-**

  - [X ] I have gone through the README(https://github.com/razorpay/razorpay-cordova)
  - [X ] I have searched for a similar issue (https://github.com/razorpay/razorpay-cordova/issues)
  - [X ] I am using the latest version of our framework (https://github.com/razorpay/razorpay-cordova/releases)
  - [X ] I have cleaned my project.

* **Specific to iOS Users :-**
  - [NA ] I have modified the module map as specified in the readme (https://github.com/razorpay/razorpay-cordova)
  - [NA ] I have deleted the contents of the derived data folder and rebuild it.
  

I am trying to add the iOS platform for an existing project (that works fine for Android). When I try to add the iOS platform I get the issue. I also get this error when I try to do a plugin add using "cordova plugin add com.razorpay.cordova --save"

I am facing the same issue on MacOS High Seirra with Xcode 10.1. Details of the config below.
Node - v8.9.3
Ionic - v3.20.0
Cordova - v8.1.2

## IDE Specs

Xcode 10.1

NA

Latest trying to add the plugin

**Comment by nssundar** [comment]
I had to completely remove the entry for RazorPay plugin from config.xml, package.json and package-lock.json and then the plugin add worked.

**Comment by iThink32** [comment]
@nssundar I generally use npm update to update the Cordova version on our sample app after we make a public release.I have not faced the issue you are facing before , can you provide the error that you were facing?

**Comment by nssundar** [comment]
> @nssundar I generally use npm update to update the Cordova version on our sample app after we make a public release.I have not faced the issue you are facing before , can you provide the error that you were facing?

Mine was a project that I was working on for more than 7 months. I think it was probably pointing to an older spec. When I removed the plugin and added it again it started to work. You can close this issue
