### ISSUE TITLE
Problem while uploading APK

### ISSUE THREAD

**Issue by TitikshaDaga** [razorpay/razorpay-cordova#95]
I am using razorpay for payments. Razorpay requires SMS permissions and according to the new google play store policies they are removing my application because of these permissions. Please help as I need to publish the application ASAP.
Even after updating the plugin this problem persists.
Thanks!!

**Comment by pronav** [comment]
Hi, are you using latest version of plugin? We had removed SMS permission from Android SDK manifest a while back.

**Comment by TitikshaDaga** [comment]
Yeah. I think i will check other plugins as well

**Comment by pramodjaypore** [comment]
Is SMS permission removed from V1.4.1 ?  i am using V1.4.1 and app where removed by google from play store due  to access Call Log or SMS data.

**Comment by pramodjaypore** [comment]
> I am using razorpay for payments. Razorpay requires SMS permissions and according to the new google play store policies they are removing my application because of these permissions. Please help as I need to publish the application ASAP.
> Even after updating the plugin this problem persists.
> Thanks!!

this is solved ? how to solve please help

**Comment by vibinflogesoft** [comment]
Iam facing the same issue with razorpay version1.4.1 ,my app rejected with error
**Based on our review, we found your app’s expressed user experience did not match your declared core functionality {SMS-based financial transactions (e.g., 5 digit messages), and related activity including OTP account verification for financial transactions and fraud detection}. Please remove these permissions from your app.**

**Comment by pkumar-uk** [comment]
Guys .Hopefully it helps. I use Meteor and was trying to add this plugin to my project. Meteor requires to specify the exact version. I was unable to add this plugin putting any version for the plugin. Ended up using GIT URL of the plugin for the latest version to include in the project then only it picked it up. So please check if the latest code is being picked up.

**Comment by Nautiyalsachin** [comment]
Hi @vibinflogesoft, Are you still facing this issue, you can try updating it to the latest released version.

**Comment by vivekshindhe** [comment]
Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
