### ISSUE TITLE
Bank page not load in cordova with javascript 

### ISSUE THREAD

**Issue by durgeshk8** [razorpay/razorpay-cordova#98]
ids.onclick = function(e){
	debugger;
	var amount=$("#amnt").val();
	if(amount!=""){
	var url="http://apifair11.fair11.com/api/GetOrderID/Get?amount="+amount+"";
	$.ajax({
            type: "GET",			
            url: url,
            dataType: "Json",
            success: function (resultData) {
			debugger;
	
			$("#orderid").val(resultData[0].messg);
			rzp1.open();
			e.preventDefault();
			}
	});
	}
	else{
		$("#mssg").text('Amount can not be left blank');
	}
    
}

var options = {

    "key": "rzp_test_R36Q47bgZr88q0",
    "amount": "100", /// The amount is shown in currency subunits. Actual amount is ₹599.
    "name": "Merchant Name",
    "order_id": ""+$("#orderid").val()+"", // Pass the order ID if you are using Razorpay Orders.
    "currency": "INR", // Optional. Same as the Order currency
    "description": "Purchase Description",
    "image": "/your_logo.png",
    "handler": function (response){
		debugger;
        alert(response.razorpay_payment_id);
		  window.history.back();
    },
    "prefill": {
        "name": "Xpert group Pvt. ltd.",
        "email": "thecoolkamal@gmail.com"
    },
    "notes": {
        "address": "Hello World"
    },
    "theme": {
        "color": "#041251"
    }
};
var rzp1 = new Razorpay(options);
![Screenshot_20190415-124418](https://user-images.githubusercontent.com/49582708/56113990-23f01c80-5f7d-11e9-9ba9-62657ff15e05.jpg)

But in cordova i am not using any plugin i have checkout.js

**Comment by pronav** [comment]
Hi Durgesh, you should not use web-integration library, it won't work since web library opens a popup to complete the payment which is not available in webview of a cordova based app. Please use cordova plugin.

**Comment by durgeshk8** [comment]
Witch plugin are used for this resolve this problem. Please suggest me
plugin

**Comment by pronav** [comment]
See Readme section of this repo: https://github.com/razorpay/razorpay-cordova

**Comment by Nautiyalsachin** [comment]
Closing this issue due to no response. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
