### ISSUE TITLE
xcode build issue for ios swift version

### ISSUE THREAD

**Issue by pkumar-uk** [razorpay/razorpay-cordova#99]
I am getting the following error while including the latest package for ios build

`/Plugins/com.razorpay.cordova/Razorpay.framework/Razorpay compiled with older version of Swift language (unknown ABI version 0x06) than previous files (unknown ABI version 0x07) file 'Stppeify/Plugins/com.razorpay.cordova/Razorpay.framework/Razorpay' for architecture x86_64`

I am using xcode 10.2 

Could you please confirm if this is an error

**Comment by pronav** [comment]
We've updated the plugin to include support for Swift5/XCode10.2
